# Name(s)
**Adrien Chaussabel**


**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**




1. 
2.
3.

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [3]:
import numpy as np
a = np.full((6, 4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [16]:
b = np.full((6, 4), 1)
np.fill_diagonal(b, 3)
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [25]:
print(a * b) # works because the dimensions are same
print()
print(np.dot(a, b)) # does not work because the number of columns in a does not equal the number of rows in b

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]



ValueError: shapes (6,4) and (6,4) not aligned: 4 (dim 1) != 6 (dim 0)

## Exercise 4

In [24]:
print(np.dot(a.transpose(), b)) # works because now the number of columns of a is 4, and number of rows in b is 4
print()
print(np.dot(a, b.transpose())) # does not work because number of columns of a is 6, and number of rows in b is 6

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]

[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


## Exercise 5

In [29]:
def print_something():
    print("something")

print_something()

something


## Exercise 6

In [45]:
def print_stats():
    row = np.random.randint(1, 10)
    col = np.random.randint(1, 10)
    matr = np.random.randint(0, 100, size=(row, col))
    print(matr)
    print("Mean =", np.mean(matr))
    print("Std Dev =", np.std(matr))
    print("Min =", np.min(matr))
    print("Max =", np.max(matr))
    print("Sum =", np.sum(matr))

print_stats()

[[95 65 56 49 23 46 17 18]
 [32 62 98 54 47 15 81 52]
 [94 92 40 84 24 14 74 57]
 [89 74 43 29 97 13 47  2]
 [81 95 33 34 51 63 88 74]
 [94 81  3 20 81  6 64 40]
 [74 81 69 64 89 13 52  7]
 [77 88 99 88 84 10 61 52]]
Mean = 56.234375
Std Dev = 29.136393794692147
Min = 2
Max = 99
Sum = 3599


## Exercise 7

In [5]:
def countOnesLoop(matr):
    cnt = 0
    for i in matr:
        if i == 1:
            cnt += 1
    return cnt

def countOnesWithWhere(matr):
    return np.where(matr == 1, 1, 0).sum()

print(countOnesLoop(np.array([1,2,3,4,5,1])))
print(countOnesWithWhere(np.array([1,2,3,1,4,5,1])))

2
3


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE