# Name(s)
**Adrien Chaussabel**


**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**




1. 
2.
3.

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [4]:
import numpy as np
a = np.full((6, 4), 2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [5]:
b = np.full((6, 4), 1)
np.fill_diagonal(b, 3)
b

array([[3, 1, 1, 1],
       [1, 3, 1, 1],
       [1, 1, 3, 1],
       [1, 1, 1, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Exercise 3

In [6]:
print(a * b) # works because the dimensions are same
print(np.dot(a, b)) # does not work because the number of columns in a does not equal the number of rows in b

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


ValueError: shapes (6,4) and (6,4) not aligned: 4 (dim 1) != 6 (dim 0)

## Exercise 4

In [16]:
print(np.dot(a.transpose(), b)) # works because now the number of columns of a is 4, and number of rows in b is 4
print()
print(np.dot(a, b.transpose())) # does not work because number of columns of a is 6, and number of rows in b is 6

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]

[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


## Exercise 5

In [18]:
def print_something():
    print("something")

print_something()

something


## Exercise 6

In [19]:
def print_stats():
    row = np.random.randint(1, 10)
    col = np.random.randint(1, 10)
    matr = np.random.randint(0, 100, size=(row, col))
    print(matr)
    print("Mean =", np.mean(matr))
    print("Std Dev =", np.std(matr))
    print("Min =", np.min(matr))
    print("Max =", np.max(matr))
    print("Sum =", np.sum(matr))

print_stats()

[[63 39 38]
 [42  5 94]
 [65  5 31]
 [85  1  3]
 [ 4  1 33]
 [83 90 58]
 [72 44 34]
 [ 3 70  9]]
Mean = 40.5
Std Dev = 31.20096152364539
Min = 1
Max = 94
Sum = 972


## Exercise 7

In [20]:
def countOnesLoop(matr):
    cnt = 0
    for i in matr:
        if i == 1:
            cnt += 1
    return cnt

def countOnesWithWhere(matr):
    return np.where(matr == 1, 1, 0).sum()

print(countOnesLoop(np.array([1,2,3,4,5,1])))
print(countOnesWithWhere(np.array([1,2,3,1,4,5,1])))

2
3


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [21]:
# 2 Methods to convert
import pandas as pd

df1 = pd.DataFrame(2, index = range(6), columns = range(4))
print(df1)
print("\nOr..\n")
df2 = pd.DataFrame(np.full((6, 4), 2))
print(df2)


   0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

Or..

   0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [22]:
b2 = pd.DataFrame(1, index = range(6), columns = range(4))

np.fill_diagonal(b2.values, 3)
b2

0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [23]:
# cross
print(df1.multiply(b))
# dot
df1.dot(b) # doesn't work because product shape is mismatched

   0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2


ValueError: Dot product shape mismatch, (6, 4) vs (6, 4)

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [24]:
def countOnesPD(df):
    cnt = 0
    for i in range(df.shape[0]):
        for j in range(df.shape[1]):
            if df.iloc[i, j] == 1:
                cnt += 1
    return cnt

countOnesPD(b2)

20

In [25]:
def countByWhere(df):
    return len(np.where(df==1)[0])
countByWhere(b2)

20

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [26]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [27]:
titanic_df.iloc[:, 2:3]

name
0                       Allen, Miss. Elisabeth Walton
1                      Allison, Master. Hudson Trevor
2                        Allison, Miss. Helen Loraine
3                Allison, Mr. Hudson Joshua Creighton
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...                                               ...
1304                             Zabour, Miss. Hileni
1305                            Zabour, Miss. Thamine
1306                        Zakarian, Mr. Mapriededer
1307                              Zakarian, Mr. Ortin
1308                               Zimmerman, Mr. Leo

[1309 rows x 1 columns]

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [28]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)


In [29]:
titanic_df.loc['female']

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

## Exercise 14
How do you reset the index?

In [30]:
## YOUR SOLUTION HERE
titanic_df.reset_index()

sex  pclass  survived  \
0     female       1         1   
1       male       1         1   
2     female       1         0   
3       male       1         0   
4     female       1         0   
...      ...     ...       ...   
1304  female       3         0   
1305  female       3         0   
1306    male       3         0   
1307    male       3         0   
1308    male       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 14 columns]